### ISSUE TITLE
基于Snowflake的Hash-Sharding分片算法

### ISSUE THREAD

**Issue by xydonne** [xydonne/java_util#1]
在主键为Snowflake算法生成ID时可使用。
极大简化分库分表配置
拓展库表不需要做数据迁移

原理：
根据SnowflakeID生成三个维度的值
timestamp：SnowflakeID的前42位
根据此值可以指定一个时间点，对此时间点后的库表关系进行重映射，在不做数据迁移的情况下拓展库表
databaseHash：SnowflakeID通过MurmurHash算法生成32位Hash值的前16位
最大可分65536个库（0x0000 - 0xFFFF）
tableHash：SnowflakeID通过MurmurHash算法生成32位Hash值的后16位
最大可分65536个表（0x0000 - 0xFFFF）

以下为yaml配置文件
```yaml
dataSource:
  db0: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  db1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  db2: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  db3: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

hash:
  snowflake_hash.id:
    2016-10-31T17:00:00:
      0x0000:
        database: db0
        tables:
          0x0000: t_snowflake_hash_0
          0x8000: t_snowflake_hash_1
      0x8000:
        database: db1
        tables:
          0x0000: t_snowflake_hash_2
          0x8000: t_snowflake_hash_3
    2016-11-20T17:00:00+08:
      0x0000:
        database: db2
        tables:
          0x0000: t_snowflake_hash_4
          0x8000: t_snowflake_hash_5
      0x8000:
        database: db3
        tables:
          0x0000: t_snowflake_hash_6
          0x8000: t_snowflake_hash_7
```

在此种规则下，原本的BetweenSharding没有太大意义。
所以改成新的查询方式BETWEEN #{lower} AND #{upper}
lower：
前32位（(lowerTimestamp >>> 10)-1<<32 ）
中16位（lowerDatabaseHash）
后16位（lowerTableHash）
upper：
前32位（(upperTimestamp >>> 10)+1<<32 ）
中16位（upperDatabaseHash）
后16位（upperTableHash）
表示查询lowerTimestamp到upperTimestamp时间段内，lowerDatabaseHash到upperDatabaseHash数据库分片，lowerTableHash到upperTableHash表分片的数据。

TODO：
1.配置的参数校验
2.目前走的是dynamic=true的方式，将会有一堆问题。

dynamic=true导致的问题：
1.无法写H2的单元测试，因为实际的语句是SELECT * FROM db.table，H2会把db字段当成schema，导致无法查询。
2.dynamic=true因为，
